# Generated by Django 5.1.4 on 2025-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Məhsulun adı')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qiyməti')),
                ('img', models.URLField(default='', verbose_name='Görüntüsü')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
    ]
