# Generated by Django 5.1.4 on 2025-01-09 00:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Məumat'),
        ),
    ]
